### ISSUE TITLE
GUI needs About Link with EasyABP-Version number and update Available notification

### ISSUE THREAD

**Issue by weedkiller** [EasyAbp/AbpHelper.GUI#102]
Hello can you please include an about or help section to include

1. Version Number
2. Update Available/AutoUpdate
3. Change Log / Bug Fixes

**Comment by gdlcf88** [comment]
> 1\. Version Number

The tray item shows AbpHelper GUI version number:
![image](https://user-images.githubusercontent.com/30018771/143766451-7bc7dc8a-4e0f-44ca-a687-ba5aa457f540.png)

> 2\. Update Available/AutoUpdate

![image](https://user-images.githubusercontent.com/30018771/143766578-fbd20cdb-989e-4616-b830-e108514dece7.png)

> 3\. Change Log / Bug Fixes

![image](https://user-images.githubusercontent.com/30018771/143766588-9ebb0154-7e08-486b-99e9-4d34c8bff3f1.png)

Hi @weedkiller, thanks for your feedback, the features you mentioned already exist, but I know the AbpHelper GUI may be low completion and make your experience poor.

I sincerely invite anyone who likes this project to submit a PR since it is a part-time project that needs your contributions.

**Comment by weedkiller** [comment]
Hello I would be willing to help out, but my exp. is low jr. level. Do you guys meet on zoom and code, or how can one contribute help, being new :)
